version: '3.9'
services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "deadline_bot_db"
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    expose:
      - "34175"
    ports:
      - "34175:34175"
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 34175

  app:
    build: .
    restart: always
    depends_on:
      - db
    stdin_open: true
    tty: true
