version: '3.9'
services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "deadline_bot_db"
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    restart: always
    depends_on:
      - db
    stdin_open: true
    tty: true