version: '3.9'
services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "deadline_bot_db"
      POSTGRES_PASSWORD: "71bR!WTSe9s7"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass 9BJ@rfds62n8

  app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
    env_file:
      - .env